const physicians_data = [
    {
        physicians_id: 1,
        first_name: "steven",
        last_name: "santiago",
        suffix: "M.D.",
        specialty: "podiatry",
        photo: "face-1.jpg",
        gender: "male",
        telephone: "257-852-6428",
        education: "rock university",
        office: "e5954",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 2,
        first_name: "jan",
        last_name: "sharp",
        suffix: "M.D.",
        specialty: "nephrology",
        photo: "face-2.jpg",
        gender: "female",
        telephone: "459-821-4896",
        education: "maine medical college",
        office: "e694",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 3,
        first_name: "joy",
        last_name: "mckenzie",
        suffix: "M.D.",
        specialty: "pulmonology",
        photo: "face-3.jpg",
        gender: "female",
        telephone: "125-548-9658",
        education: "st. john medical college",
        office: "f3564",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 4,
        first_name: "sophie",
        last_name: "mccormik",
        suffix: "M.D.",
        specialty: "general surgery",
        photo: "face-4.jpg",
        gender: "female",
        telephone: "128-745-3654",
        education: "springfield university",
        office: "e9633",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 5,
        first_name: "dave",
        last_name: "morrison",
        suffix: "D.O.",
        specialty: "neurosurgery",
        photo: "face-5.jpg",
        gender: "male",
        telephone: "456-852-6479",
        education: "blue mountain state university",
        office: "f65",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 6,
        first_name: "leigh",
        last_name: "morton",
        suffix: "D.O.",
        specialty: "internal medicine",
        photo: "face-6.jpg",
        gender: "female",
        telephone: "945-614-7526",
        education: "monsters school of medicine",
        office: "e123",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 7,
        first_name: "jamie",
        last_name: "rodgers",
        suffix: "M.D.",
        specialty: "urology",
        photo: "face-7.jpg",
        gender: "female",
        telephone: "845-319-7425",
        education: "empire state university",
        office: "h741",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 8,
        first_name: "horace",
        last_name: "roberts",
        suffix: "M.D.",
        specialty: "anesthesiology",
        photo: "face-8.jpg",
        gender: "male",
        telephone: "345-542-6248",
        education: "fair college",
        office: "g12521",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 9,
        first_name: "clara",
        last_name: "burke",
        suffix: "D.O.",
        specialty: "maternal, fetal medicine",
        photo: "face-9.jpg",
        gender: "female",
        telephone: "545-758-8524",
        education: "empire medical school",
        office: "e5677",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 10,
        first_name: "geneva",
        last_name: "curtis",
        suffix: "M.D.",
        specialty: "cardiology",
        photo: "face-10.jpg",
        gender: "female",
        telephone: "914-536-7428",
        education: "greendale school of medicine",
        office: "f964",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 11,
        first_name: "meghan",
        last_name: "brewer",
        suffix: "M.D.",
        specialty: "gastroenterology",
        photo: "face-11.jpg",
        gender: "female",
        telephone: "345-635-4896",
        education: "pennyham state university",
        office: "g14",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 12,
        first_name: "vernon",
        last_name: "owens",
        suffix: "M.D.",
        specialty: "family medicine",
        photo: "face-12.jpg",
        gender: "male",
        telephone: "354-965-7485",
        education: "hudson medical school",
        office: "e8699",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 13,
        first_name: "lynn",
        last_name: "greene",
        suffix: "M.D.",
        specialty: "pediatrics",
        photo: "face-13.jpg",
        gender: "female",
        telephone: "384-962-7484",
        education: "quohog health sciences university",
        office: "f1478",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 14,
        first_name: "heather",
        last_name: "sherman",
        suffix: "D.O.",
        specialty: "internal medicine",
        photo: "face-14.jpg",
        gender: "female",
        telephone: "504-365-9757",
        education: "city university",
        office: "g574",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 15,
        first_name: "johnathan",
        last_name: "erikson",
        suffix: "M.D.",
        specialty: "gynecology",
        photo: "face-15.jpg",
        gender: "male",
        telephone: "364-242-1585",
        education: "cool state university",
        office: "e469",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 16,
        first_name: "joe",
        last_name: "chandler",
        suffix: "D.O.",
        specialty: "dermatology",
        photo: "face-16.jpg",
        gender: "male",
        telephone: "125-458-6585",
        education: "medical college of hill valley",
        office: "h496",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    },
    {
        physicians_id: 17,
        first_name: "angeline",
        last_name: "collins",
        suffix: "D.O.",
        specialty: "neurology",
        photo: "face-17.jpg",
        gender: "female",
        telephone: "852-456-9517",
        education: "ross medical college",
        office: "h9677",
        info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa molestiae illo laboriosam libero! Itaque unde ex eaque repellendus saepe rem et deleniti rerum nesciunt, aliquam nobis eligendi harum eum minima sed inventore asperiores officiis facilis perferendis quas fuga nostrum omnis dolorum. Odio eligendi ipsa consequatur exercitationem iure numquam aut aliquid."
    }
];

export default physicians_data;
